### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sindresorhus** [LitoMore/kap-fanfou#6]
- `context.setProgress('Uploading…');` should be placed above `await Fanfou.upload(token, filePath);`. Don't show status until you're actually doing the thing you describe.
- You don't have to try/catch [here](https://github.com/LitoMore/kap-fanfou/blob/445a21e36d89b50560c9ed2b1a1f1a4c00f7c8cf/index.js#L31). We catch any error from plugins and display a notification.
- `default: 'Your consumer key',` is incorrect. That is not a default value. You should instead use the `description` key for this: `description: 'Your consumer key',`.
- The `useNofanConfig` config needs a `description` key with a description of what it actually that. It's not clear from the title.

**Comment by LitoMore** [comment]
@sindresorhus Thank you Sindre!
